#!/usr/bin/env python3
"""Build Danish (da_DK) PO/MO files from the plugin POT template."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

try:
    import polib
except ImportError:
    print("Install polib: pip3 install polib", file=sys.stderr)
    sys.exit(1)

from da_translations_supplement import SUPPLEMENT

PLUGIN_ROOT = Path(__file__).resolve().parent.parent
POT_FILE = PLUGIN_ROOT / "languages" / "prikogstreg-online-invitations.pot"
PO_FILE = PLUGIN_ROOT / "languages" / "prikogstreg-online-invitations-da_DK.po"
MO_FILE = PLUGIN_ROOT / "languages" / "prikogstreg-online-invitations-da_DK.mo"
BAK_FILE = PO_FILE.with_suffix(".po.bak")

# Complete Danish (da_DK) translations keyed by English msgid.
TRANSLATIONS: dict[str, str] = {
    '%1$d of %2$d ready': '%1$d af %2$d klar',
    '%1$d of %2$d reserved': '%1$d af %2$d reserveret',
    '%1$d photos · %2$d pending': '%1$d fotos · %2$d afventer',
    '%1$d yes · %2$d no': '%1$d ja · %2$d nej',
    'A database update is in progress. Some invitation features may be temporarily unavailable.': 'En databaseopdatering er i gang. Nogle invitationsfunktioner kan være midlertidigt utilgængelige.',
    'A matching e-mail already exists in your address book.': 'En matchende e-mail findes allerede i din adressebog.',
    'Action Scheduler was not detected. Scheduled invitation tasks will not run until WooCommerce Action Scheduler is available.': 'Action Scheduler blev ikke fundet. Planlagte invitationsopgaver kører ikke, før WooCommerce Action Scheduler er tilgængelig.',
    'Actions': 'Handlinger',
    'Activate and save a PDF Builder template for this product.': 'Aktivér og gem en PDF Builder-skabelon for dette produkt.',
    'Active': 'Aktiv',
    'Actor': 'Aktør',
    'Add contact': 'Tilføj kontakt',
    'Add gift': 'Tilføj gave',
    'Add gifts to your wishlist or link an external Ønskeskyen list.': 'Tilføj gaver til din ønskeliste, eller link til en ekstern Ønskeskyen-liste.',
    'Add guest': 'Tilføj gæst',
    'Add guests': 'Tilføj gæster',
    'Add guests manually or import a CSV to start sending invitations.': 'Tilføj gæster manuelt, eller importér en CSV for at begynde at sende invitationer.',
    'Add guests to send personal invitation links.': 'Tilføj gæster for at sende personlige invitationslinks.',
    'Add guests, import a CSV list, and send personal invitation links.': 'Tilføj gæster, importér en CSV-liste, og send personlige invitationslinks.',
    'Add selected to this project': 'Tilføj valgte til dette projekt',
    'Add the information guests will see on your invitation and RSVP page.': 'Tilføj de oplysninger, gæsterne skal se på din invitation og RSVP-side.',
    'Add title and date': 'Tilføj titel og dato',
    'Add your event title and date before publishing.': 'Tilføj begivenhedstitel og dato, før du publicerer.',
    'Address book': 'Adressebog',
    'Address line 1': 'Adresselinje 1',
    'All': 'Alle',
    'All invitations': 'Alle invitationer',
    'Allow purchase without a connected PDF Builder template. The product page shows a placeholder preview during testing.': 'Tillad køb uden tilkoblet PDF Builder-skabelon. Produktsiden viser en pladsholderforhåndsvisning under test.',
    'An account is required to purchase an online invitation. Please create an account or log in to continue.': 'Der kræves en konto for at købe en online invitation. Opret en konto eller log ind for at fortsætte.',
    'Anonymized guest record #%d.': 'Anonymiserede gæsteregistrering #%d.',
    'Another address-book contact already uses this e-mail.': 'En anden kontakt i adressebogen bruger allerede denne e-mail.',
    'Another guest on this project already uses this e-mail address.': 'En anden gæst på dette projekt bruger allerede denne e-mailadresse.',
    'Approve': 'Godkend',
    'Approved': 'Godkendt',
    'Archive project': 'Arkivér projekt',
    'Archive selected': 'Arkivér valgte',
    'Archive, restore, or permanently delete this invitation project.': 'Arkivér, gendan eller permanent slet dette invitationsprojekt.',
    'Archived': 'Arkiveret',
    'Archiving stops public access and pending deliveries. Your data is kept until you delete the project.': 'Arkivering stopper offentlig adgang og afventende leveringer. Dine data bevares, indtil du sletter projektet.',
    'Attendees': 'Deltagere',
    'Attending': 'Deltager',
    'Audit reason (optional)': 'Revisionsårsag (valgfrit)',
    'Back to all projects': 'Tilbage til alle projekter',
    'Back to list': 'Tilbage til listen',
    'Back to online invitations': 'Tilbage til online invitationer',
    'Basics': 'Grundlæggende',
    'Bounced': 'Returneret',
    'Builder': 'Builder',
    'Builder integration status': 'Builder-integrationsstatus',
    'Builder template and invitation presets are configured.': 'Builder-skabelon og invitationsforudindstillinger er konfigureret.',
    'Choose photos (JPEG, PNG, or WebP)': 'Vælg fotos (JPEG, PNG eller WebP)',
    'Classic envelope': 'Klassisk konvolut',
    'Clear expiry override': 'Ryd tilsidesættelse af udløb',
    'Columns: display name, email, phone, party label, number of guests.': 'Kolonner: visningsnavn, e-mail, telefon, gruppelabel, antal gæster.',
    'Columns: display name, email, phone, party label.': 'Kolonner: visningsnavn, e-mail, telefon, gruppelabel.',
    'Coming soon': 'Kommer snart',
    'Comment (optional)': 'Kommentar (valgfrit)',
    'Complete': 'Fuldført',
    'Complete design first': 'Fuldfør design først',
    'Complete your design and event details before publishing.': 'Fuldfør dit design og begivenhedsdetaljer, før du publicerer.',
    'Complete your design and event details to generate a preview.': 'Fuldfør dit design og begivenhedsdetaljer for at generere en forhåndsvisning.',
    'Configuration incomplete': 'Konfiguration ufuldstændig',
    'Confirm import': 'Bekræft import',
    'Confirmation after a guest submits or changes an RSVP.': 'Bekræftelse efter en gæst afgiver eller ændrer et RSVP.',
    'Contacts': 'Kontakter',
    'Continue': 'Fortsæt',
    'Continue setup': 'Fortsæt opsætning',
    'Controls the animated envelope style on the public invitation.': 'Styrer den animerede konvolutstil på den offentlige invitation.',
    'Copy link': 'Kopiér link',
    'Counts': 'Antal',
    'Created': 'Oprettet',
    'Customer': 'Kunde',
    'Customise your invitation. Changes save automatically when you use the editor save action.': 'Tilpas din invitation. Ændringer gemmes automatisk, når du gemmer i editoren.',
    'Dates are stored in your chosen timezone.': 'Datoer gemmes i din valgte tidszone.',
    'Deactivated': 'Deaktiveret',
    'Dear guest': 'Kære gæst',
    'Declined': 'Afvist',
    'Default locale': 'Standard landestandard',
    'Delete permanently': 'Slet permanent',
    'Delete project permanently': 'Slet projekt permanent',
    'Deleted invitation project #%d.': 'Slettede invitationsprojekt #%d.',
    'Delivery failures': 'Leveringsfejl',
    'Demo invitation': 'Demo-invitation',
    'Demo invitation queued for your email.': 'Demo-invitation sat i kø til din e-mail.',
    'Description': 'Beskrivelse',
    'Design': 'Design',
    'Design editing is not available for this project.': 'Designredigering er ikke tilgængelig for dette projekt.',
    'Design editor unavailable': 'Designeditor utilgængelig',
    'Design imported': 'Design importeret',
    'Design needs attention': 'Design kræver opmærksomhed',
    'Details saved': 'Detaljer gemt',
    'Dietary notes (optional)': 'Kostnoter (valgfrit)',
    'Display name': 'Visningsnavn',
    'Download': 'Download',
    'Draft': 'Kladde',
    'Draft preview': 'Kladdeforhåndsvisning',
    'E-mail': 'E-mail',
    'E-mail (optional)': 'E-mail (valgfrit)',
    'Edit': 'Redigér',
    'Edit contact': 'Redigér kontakt',
    'Edit design': 'Redigér design',
    'Edit gift': 'Redigér gave',
    'Editing disabled': 'Redigering deaktiveret',
    'Effective expiry': 'Effektiv udløbsdato',
    'Enable internal wishlist': 'Aktivér intern ønskeliste',
    'Envelope preset': 'Konvolutforudindstilling',
    'Envelope preview reference': 'Reference til konvolutforhåndsvisning',
    'Envelope: %s': 'Konvolut: %s',
    'Event': 'Begivenhed',
    'Event date': 'Begivenhedsdato',
    'Event details': 'Begivenhedsdetaljer',
    'Event details cannot be edited for this project.': 'Begivenhedsdetaljer kan ikke redigeres for dette projekt.',
    'Event details saved.': 'Begivenhedsdetaljer gemt.',
    'Event end (local)': 'Begivenhedsslut (lokal tid)',
    'Event start (local)': 'Begivenhedsstart (lokal tid)',
    'Event title': 'Begivenhedstitel',
    'Event title and date are set.': 'Begivenhedstitel og dato er angivet.',
    'Example: Europe/Copenhagen': 'Eksempel: Europe/Copenhagen',
    'Expired': 'Udløbet',
    'Expires': 'Udløber',
    'Expiry override (UTC Y-m-d H:i:s)': 'Tilsidesættelse af udløb (UTC Y-m-d H:i:s)',
    'Export CSV': 'Eksportér CSV',
    'External Ønskeskyen URL (optional)': 'Ekstern Ønskeskyen-URL (valgfrit)',
    'Extra information': 'Ekstra information',
    'Filter': 'Filtrér',
    'Finish setup': 'Afslut opsætning',
    'Floral background': 'Blomstret baggrund',
    'Generic background preset': 'Generel baggrundsforudindstilling',
    'Generic link': 'Generisk link',
    'Geometric background': 'Geometrisk baggrund',
    'Get started': 'Kom i gang',
    'Go to design': 'Gå til design',
    'Go to publish': 'Gå til publicering',
    'Guest': 'Gæst',
    'Guest #%d': 'Gæst #%d',
    'Guest CSV file': 'Gæste-CSV-fil',
    'Guest invitation': 'Gæsteinvitation',
    'Guest list': 'Gæsteliste',
    'Guest personal links are sent by e-mail. We store only hashed tokens, not raw invitation URLs, in our database.': "Personlige gæstelinks sendes via e-mail. Vi gemmer kun hashede tokens, ikke rå invitations-URL'er, i databasen.",
    'Guest photo metadata': 'Metadata for gæstefotos',
    'Guest photo uploads are moderated by the project owner before download. Photos are not published in a public gallery by default.': 'Gæstefotos modereres af projektets ejer, før de kan downloades. Fotos publiceres som standard ikke i et offentligt galleri.',
    'Guest photo uploads enabled by default': 'Gæstefotoupload aktiveret som standard',
    'Guest photo uploads will appear here for moderation.': 'Gæstefotouploads vises her til moderation.',
    'Guest photos': 'Gæstefotos',
    'Guest response received': 'Gæstesvar modtaget',
    'Guests': 'Gæster',
    'Guests can view and respond to your published invitation.': 'Gæster kan se og svare på din publicerede invitation.',
    'Guests: %1$d · Wishlist: %2$d · Photos: %3$d · Deliveries: %4$d': 'Gæster: %1$d · Ønskeliste: %2$d · Fotos: %3$d · Leveringer: %4$d',
    'Hard delete': 'Permanent sletning',
    'Healthy': 'Sund',
    'Hidden': 'Skjult',
    'How many people this invitation is for. The guest confirms the number when they respond.': 'Hvor mange personer denne invitation er til. Gæsten bekræfter antallet, når de svarer.',
    'How your event appears to guests.': 'Sådan vises din begivenhed for gæsterne.',
    'https://prikogstreg.dk/': 'https://prikogstreg.dk/',
    'Image URL (optional)': 'Billede-URL (valgfrit)',
    'Import CSV': 'Importér CSV',
    'Import is pending or failed — contact support if this persists.': 'Import afventer eller mislykkedes — kontakt support, hvis det fortsætter.',
    'Import needs attention': 'Import kræver opmærksomhed',
    'Import pending': 'Import afventer',
    'In progress': 'I gang',
    'Internal wishlist enabled by default': 'Intern ønskeliste aktiveret som standard',
    'Invalid save payload from editor.': 'Ugyldige gemmedata fra editoren.',
    'Invitation': 'Invitation',
    'Invitation #%1$d — %2$s — %3$s': 'Invitation #%1$d — %2$s — %3$s',
    'Invitation address book': 'Invitationsadressebog',
    'Invitation builder data is missing or invalid. Please return to the cart and customise the product again.': 'Invitationsbuilder-data mangler eller er ugyldige. Gå tilbage til kurven og tilpas produktet igen.',
    'Invitation configuration is incomplete.': 'Invitationskonfigurationen er ufuldstændig.',
    'Invitation delivery history': 'Invitationsleveringshistorik',
    'Invitation Project': 'Invitationsprojekt',
    'Invitation project #%d': 'Invitationsprojekt #%d',
    'Invitation project details': 'Detaljer for invitationsprojekt',
    'Invitation project support': 'Support for invitationsprojekt',
    'Invitation Projects': 'Invitationsprojekter',
    'Invitation unavailable': 'Invitation utilgængelig',
    'Invitation update (%s)': 'Invitationsopdatering (%s)',
    'Issues detected': 'Problemer registreret',
    'item': 'vare',
    'Last error': 'Seneste fejl',
    'Launch': 'Lancering',
    'Live': 'Live',
    'Make your invitation live when design and event details are ready.': 'Gør din invitation live, når design og begivenhedsdetaljer er klar.',
    'Manage': 'Administrér',
    'Manage your purchased invitation projects.': 'Administrér dine købte invitationsprojekter.',
    'Maybe': 'Måske',
    'Minimal envelope': 'Minimal konvolut',
    'Modern envelope': 'Moderne konvolut',
    'Name': 'Navn',
    'Name or email': 'Navn eller e-mail',
    'Needs attention': 'Kræver opmærksomhed',
    'Neutral background': 'Neutral baggrund',
    'New guest photo': 'Nyt gæstefoto',
    'New guest photo for {event_title}': 'Nyt gæstefoto for {event_title}',
    'New RSVP for {event_title}': 'Nyt RSVP for {event_title}',
    'Next': 'Næste',
    'Next step': 'Næste trin',
    'No': 'Nej',
    'No contacts yet': 'Ingen kontakter endnu',
    'No e-mail address provided.': 'Ingen e-mailadresse angivet.',
    'No failed or skipped deliveries.': 'Ingen mislykkede eller sprunget over leveringer.',
    'No gifts yet': 'Ingen gaver endnu',
    'No guests yet': 'Ingen gæster endnu',
    'No invitation projects match this filter.': 'Ingen invitationsprojekter matcher dette filter.',
    'No linked project row.': 'Ingen tilknyttet projektrad.',
    'No matching invitation data found for this e-mail.': 'Ingen matchende invitationsdata fundet for denne e-mail.',
    'No photos in this view': 'Ingen fotos i denne visning',
    'No responses yet': 'Ingen svar endnu',
    'Not attending': 'Deltager ikke',
    'Not published': 'Ikke publiceret',
    'Not sent': 'Ikke sendt',
    'Notes': 'Noter',
    'Notifies the organiser when a guest responds.': 'Underretter arrangøren, når en gæst svarer.',
    'Notifies the organiser when a guest uploads a photo.': 'Underretter arrangøren, når en gæst uploader et foto.',
    'Number attending': 'Antal deltagere',
    'Number of guests': 'Antal gæster',
    'Online Invitation': 'Online invitation',
    'Online invitation': 'Online invitation',
    'Online Invitation product is incomplete:': 'Online Invitation-produktet er ufuldstændigt:',
    'Online invitation projects': 'Online invitationsprojekter',
    'Online invitation quantity cannot be changed.': 'Antal online invitationer kan ikke ændres.',
    'Online Invitations': 'Online invitationer',
    'Online invitations': 'Online invitationer',
    'Online invitations are not supported via the Checkout Block in this release.': 'Online invitationer understøttes ikke via Checkout Block i denne udgivelse.',
    'Online invitations can only be purchased one at a time.': 'Online invitationer kan kun købes én ad gangen.',
    'Online invitations cannot be purchased through the block-based checkout yet. Please use the classic checkout page or contact support.': 'Online invitationer kan endnu ikke købes via den blokbaserede checkout. Brug den klassiske checkout-side eller kontakt support.',
    'Online invitations dashboard (coming soon).': 'Online invitations-dashboard (kommer snart).',
    'Online invitations require a customer account. You will receive a secure link to set your password after checkout — we never send passwords by e-mail.': 'Online invitationer kræver en kundekonto. Du modtager et sikkert link til at oprette din adgangskode efter checkout — vi sender aldrig adgangskoder via e-mail.',
    'Open in My Account': 'Åbn i Min konto',
    'Open invitation': 'Åbn invitation',
    'Open PDF Builder customizer': 'Åbn PDF Builder-tilpasning',
    'Open support view in My Account': 'Åbn supportvisning i Min konto',
    'Opened': 'Åbnet',
    'Optional': 'Valgfrit',
    'Optional admin reference for preview assets (slug, note, or internal asset key).': 'Valgfri admin-reference til forhåndsvisningsaktiver (slug, note eller internt aktivnøgle).',
    'Optional external wishlist links (for example Ønskeskyen) open third-party websites. We do not synchronize data with those services.': 'Valgfrie eksterne ønskeliste-links (for eksempel Ønskeskyen) åbner tredjepartswebsteder. Vi synkroniserer ikke data med disse tjenester.',
    'Optional — let guests reserve gifts or link to an external wishlist.': 'Valgfrit — lad gæster reservere gaver eller link til en ekstern ønskeliste.',
    'Optional — review uploads from guests. Approved photos are not shown in a public gallery.': 'Valgfrit — gennemgå uploads fra gæster. Godkendte fotos vises ikke i et offentligt galleri.',
    'Optional — save private contacts you can reuse across invitations.': 'Valgfrit — gem private kontakter, som du kan genbruge på tværs af invitationer.',
    'Order': 'Ordre',
    'Organiser display name': 'Arrangørens visningsnavn',
    'Organizer RSVP notification': 'Arrangørnotifikation om RSVP',
    'override': 'tilsidesættelse',
    'Overview': 'Overblik',
    'Owner': 'Ejer',
    'Owner demo-to-self preview link.': 'Ejerens demo-forhåndsvisningslink til sig selv.',
    'Page %1$d of %2$d': 'Side %1$d af %2$d',
    'Party label': 'Gruppelabel',
    'PDF / Online invitation will show here': 'PDF / online invitation vises her',
    'PDF Builder is optional. The storefront shows a placeholder preview until a template is connected.': 'PDF Builder er valgfrit. Butikken viser en pladsholderforhåndsvisning, indtil en skabelon er tilkoblet.',
    'PDF Builder optional (testing)': 'PDF Builder valgfrit (test)',
    'Pending': 'Afventer',
    'Pending event date': 'Afventer begivenhedsdato',
    'Permanent deletion removes invitation files, guests, photos, and related records. Your WooCommerce order may still be retained for legal purposes.': 'Permanent sletning fjerner invitationsfiler, gæster, fotos og relaterede registreringer. Din WooCommerce-ordre kan stadig opbevares af juridiske årsager.',
    'Permanently delete this project and all data?': 'Permanent slet dette projekt og alle data?',
    'Personal invitation link (copy now — shown once):': 'Personligt invitationslink (kopiér nu — vises kun én gang):',
    'Personal link (save for later):': 'Personligt link (gem til senere):',
    'Personal invitation link for a guest.': 'Personligt invitationslink til en gæst.',
    'Phone': 'Telefon',
    'Photo': 'Foto',
    'Photo upload notification': 'Notifikation om fotoupload',
    'Photo uploads are not available for this invitation.': 'Fotoupload er ikke tilgængelig for denne invitation.',
    'Photos': 'Fotos',
    'Photos uploaded. They will appear after organiser approval.': 'Fotos uploadet. De vises, når arrangøren har godkendt dem.',
    'Please choose whether you are attending.': 'Vælg venligst, om du deltager.',
    'Please customise the invitation in the PDF Builder before adding it to your cart.': 'Tilpas venligst invitationen i PDF Builder, før du lægger den i kurven.',
    'Please enter how many people are attending.': 'Angiv venligst, hvor mange der deltager.',
    'Please enter your name before reserving a gift.': 'Angiv venligst dit navn, før du reserverer en gave.',
    'Please enter your name before uploading photos.': 'Angiv venligst dit navn, før du uploader fotos.',
    'Please enter your name.': 'Angiv venligst dit navn.',
    'Please respond by %s.': 'Svar venligst senest %s.',
    'Practical information': 'Praktisk information',
    'Preview': 'Forhåndsvisning',
    'Preview available': 'Forhåndsvisning tilgængelig',
    'Preview import': 'Forhåndsvis import',
    'Preview not ready': 'Forhåndsvisning ikke klar',
    'Previous': 'Forrige',
    'Prik & Streg': 'Prik & Streg',
    'Prikogstreg Online Invitations': 'Prikogstreg Online Invitations',
    'Prikogstreg Online Invitations could not complete a database migration. Online invitation data may be unavailable until the migration succeeds.': 'Prikogstreg Online Invitations kunne ikke fuldføre en databasemigrering. Online invitationsdata er muligvis utilgængelige, indtil migreringen lykkes.',
    'Prikogstreg Online Invitations detected an incompatible PDF Builder integration service. Online invitation features are disabled until the adapter is updated.': 'Prikogstreg Online Invitations har registreret en inkompatibel PDF Builder-integrationstjeneste. Online invitationsfunktioner er deaktiveret, indtil adapteren opdateres.',
    'Prikogstreg Online Invitations is missing Composer dependencies. Run composer install in the plugin directory.': 'Prikogstreg Online Invitations mangler Composer-afhængigheder. Kør composer install i plugin-mappen.',
    'Prikogstreg Online Invitations is waiting for the PDF Builder integration adapter (bpp/integration/service). Online invitation features are not active yet.': 'Prikogstreg Online Invitations venter på PDF Builder-integrationsadapteren (bpp/integration/service). Online invitationsfunktioner er endnu ikke aktive.',
    'Prikogstreg Online Invitations requires PHP %s or newer.': 'Prikogstreg Online Invitations kræver PHP %s eller nyere.',
    'Prikogstreg Online Invitations requires WooCommerce %s or newer.': 'Prikogstreg Online Invitations kræver WooCommerce %s eller nyere.',
    'Prikogstreg Online Invitations requires WooCommerce High-Performance Order Storage (HPOS). Enable it under WooCommerce → Settings → Advanced → Features.': 'Prikogstreg Online Invitations kræver WooCommerce High-Performance Order Storage (HPOS). Aktivér det under WooCommerce → Indstillinger → Avanceret → Funktioner.',
    'Prikogstreg Online Invitations requires WooCommerce to be installed and active.': 'Prikogstreg Online Invitations kræver, at WooCommerce er installeret og aktivt.',
    'Prikogstreg Online Invitations requires WordPress %s or newer.': 'Prikogstreg Online Invitations kræver WordPress %s eller nyere.',
    'Privacy and project lifecycle': 'Privatliv og projektlivscyklus',
    'Private draft preview — opens are not tracked.': 'Privat kladdeforhåndsvisning — åbninger spores ikke.',
    'Product': 'Produkt',
    'Product URL (optional)': 'Produkt-URL (valgfrit)',
    'Project': 'Projekt',
    'Project #%1$d partial cleanup: %2$s': 'Projekt #%1$d delvis oprydning: %2$s',
    'Project activity log': 'Projektaktivitetslog',
    'Project guests (owner export)': 'Projektgæster (ejerexport)',
    'Project ID': 'Projekt-ID',
    'Project import retry completed successfully.': 'Genforsøg på projektimport gennemført.',
    'Project import retry failed. Check the project error code and order payload.': 'Genforsøg på projektimport mislykkedes. Tjek projektets fejlkode og ordrens data.',
    'Project list pagination': 'Sideinddeling for projektliste',
    'Project not found.': 'Projekt ikke fundet.',
    'Project sections': 'Projektafsnit',
    'Project status': 'Projektstatus',
    'Project welcome': 'Projektvelkomst',
    'Projects remain available to the owner after the event for a limited period, then may be marked expired. Expiry does not automatically delete your data.': 'Projekter forbliver tilgængelige for ejeren i en begrænset periode efter begivenheden og kan derefter markeres som udløbet. Udløb sletter ikke automatisk dine data.',
    'Public contact email': 'Offentlig kontakt-e-mail',
    'Publication': 'Publicering',
    'Publish': 'Publicér',
    'Publish invitation': 'Publicér invitation',
    'Publish when your project is ready to share.': 'Publicér, når dit projekt er klar til at deles.',
    'Published': 'Publiceret',
    'published': 'publiceret',
    'Publishing is not available for this project.': 'Publicering er ikke tilgængelig for dette projekt.',
    'Publishing unavailable': 'Publicering utilgængelig',
    'Quantity requested': 'Ønsket antal',
    'Rate-limiting identifiers are stored briefly using hashed values and expire automatically.': "Ratebegrænsnings-id'er gemmes kortvarigt som hashede værdier og udløber automatisk.",
    'Ready for purchase': 'Klar til køb',
    'Ready to edit': 'Klar til redigering',
    'Ready to import %d guests.': 'Klar til at importere %d gæster.',
    'Ready to publish?': 'Klar til at publicere?',
    'Recent changes': 'Seneste ændringer',
    'Recent events': 'Seneste hændelser',
    'Reject': 'Afvis',
    'Rejected': 'Afvist',
    'Release my reservation': 'Frigiv min reservation',
    'Reminder before the RSVP deadline.': 'Påmindelse før RSVP-fristen.',
    'Reminder: please respond to {event_title}': 'Påmindelse: svar venligst på {event_title}',
    'Removed %d address book contacts.': 'Fjernede %d adressebogskontakter.',
    'Resend welcome': 'Gensend velkomst',
    'Reserve': 'Reservér',
    'Responded': 'Har svaret',
    'Response': 'Svar',
    'Responses': 'Svar',
    'Responses appear here when guests RSVP to your invitation.': "Svar vises her, når gæster RSVP'er til din invitation.",
    'Responses pagination': 'Sideinddeling for svar',
    'Restore': 'Gendan',
    'Restore from archive': 'Gendan fra arkiv',
    'Restore project': 'Gendan projekt',
    'Restrict': 'Begræns',
    'Restricted': 'Begrænset',
    'Retry import': 'Prøv import igen',
    'Rotate generic token': 'Rotér generisk token',
    'RSVP': 'RSVP',
    'RSVP confirmation': 'RSVP-bekræftelse',
    'RSVP deadline (local)': 'RSVP-frist (lokal tid)',
    'RSVP received': 'RSVP modtaget',
    'RSVP reminder': 'RSVP-påmindelse',
    'RSVP reminder offset (days)': 'RSVP-påmindelse (dage før)',
    'Save contact': 'Gem kontakt',
    'Save contacts here to quickly add them to future guest lists.': 'Gem kontakter her for hurtigt at tilføje dem til fremtidige gæstelister.',
    'Save endpoint unavailable.': 'Gem-endepunkt utilgængeligt.',
    'Save event details': 'Gem begivenhedsdetaljer',
    'Save failed. Check your connection and try again.': 'Kunne ikke gemme. Tjek din forbindelse og prøv igen.',
    'Save guest': 'Gem gæst',
    'Save item': 'Gem vare',
    'Save wishlist settings': 'Gem indstillinger for ønskeliste',
    'Saved.': 'Gemt.',
    'Saving your response…': 'Gemmer dit svar…',
    'Saving…': 'Gemmer…',
    'Schema': 'Skema',
    'Search': 'Søg',
    'Search contacts': 'Søg kontakter',
    'Select': 'Vælg',
    'Select a preset…': 'Vælg en forudindstilling…',
    'Select a valid background preset.': 'Vælg en gyldig baggrundsforudindstilling.',
    'Select a valid envelope preset.': 'Vælg en gyldig konvolutforudindstilling.',
    'Select all contacts': 'Vælg alle kontakter',
    'Select all guests': 'Vælg alle gæster',
    'selected': 'valgt',
    'Send demo to myself': 'Send demo til mig selv',
    'Send demo to yourself': 'Send demo til dig selv',
    'Send invitations to selected': 'Send invitationer til valgte',
    'Send response': 'Send svar',
    'Sends a private preview link to your email. No guest RSVP or open tracking.': 'Sender et privat forhåndsvisningslink til din e-mail. Ingen gæste-RSVP eller åbningssporing.',
    'Sent': 'Sendt',
    'Sent once when an invitation project is ready in My Account.': 'Sendes én gang, når et invitationsprojekt er klar i Min konto.',
    'Set expiry override': 'Angiv tilsidesættelse af udløb',
    'Settings': 'Indstillinger',
    'Setup': 'Opsætning',
    'Setup checklist': 'Opsætnings-tjekliste',
    'Setup progress': 'Opsætningsfremskridt',
    'Share photos from the event. Uploads are private until the organiser approves them.': 'Del fotos fra begivenheden. Uploads er private, indtil arrangøren godkender dem.',
    'Show more details': 'Vis flere detaljer',
    'Show who reserved each gift (off preserves surprise)': 'Vis hvem der har reserveret hver gave (fra bevarer overraskelsen)',
    'state': 'tilstand',
    'Status': 'Status',
    'Storage health': 'Lagringstilstand',
    'Support action completed.': 'Supporthandling gennemført.',
    'Support action could not be completed.': 'Supporthandling kunne ikke gennemføres.',
    'Support actions': 'Supporthandlinger',
    'Support view — address book access has been logged.': 'Supportvisning — adgang til adressebog er logget.',
    'Support view — you are viewing this project as shop staff.': 'Supportvisning — du ser dette projekt som butikspersonale.',
    'Testing without PDF Builder': 'Test uden PDF Builder',
    'Thank you — we have recorded that you cannot attend.': 'Tak — vi har registreret, at du desværre ikke kan deltage.',
    'Thank you — your response has been recorded.': 'Tak — dit svar er registreret.',
    'That gift is no longer available in the requested quantity.': 'Den gave er ikke længere tilgængelig i det ønskede antal.',
    'The attendee count is not valid.': 'Antallet af deltagere er ikke gyldigt.',
    'The e-mail address is not valid.': 'E-mailadressen er ikke gyldig.',
    'The PDF Builder integration adapter is not available. Online invitation features are disabled.': 'PDF Builder-integrationsadapteren er ikke tilgængelig. Online invitationsfunktioner er deaktiveret.',
    'The PDF Builder integration is not active for this product. Contact support if you expected a design editor here.': 'PDF Builder-integrationen er ikke aktiv for dette produkt. Kontakt support, hvis du forventede en designeditor her.',
    'The PDF Builder integration is unavailable. Design editing is disabled until the adapter is active.': 'PDF Builder-integrationen er utilgængelig. Designredigering er deaktiveret, indtil adapteren er aktiv.',
    'The RSVP deadline has passed. Your recorded response is shown below.': 'RSVP-fristen er overskredet. Dit registrerede svar vises nedenfor.',
    'The RSVP deadline has passed. Your response can no longer be changed.': 'RSVP-fristen er overskredet. Dit svar kan ikke længere ændres.',
    'The wishlist is not available for this invitation.': 'Ønskelisten er ikke tilgængelig for denne invitation.',
    'This cannot be undone. Delete this project and all related data?': 'Dette kan ikke fortrydes. Slet dette projekt og alle relaterede data?',
    'This invitation is not available.': 'Denne invitation er ikke tilgængelig.',
    'This invitation project could not be found.': 'Dette invitationsprojekt blev ikke fundet.',
    'This online invitation product is not ready for purchase yet.': 'Dette online invitationsprodukt er endnu ikke klar til køb.',
    'This project has been archived. Public access and scheduled sends are stopped.': 'Dette projekt er arkiveret. Offentlig adgang og planlagte udsendelser er stoppet.',
    'This project has been restored from archive.': 'Dette projekt er gendannet fra arkiv.',
    'This project import failed and needs support attention before you can continue.': 'Import af dette projekt mislykkedes og kræver support, før du kan fortsætte.',
    'This section is not available yet. It will be added in an upcoming release.': 'Dette afsnit er endnu ikke tilgængeligt. Det tilføjes i en kommende udgivelse.',
    'This section will be available in a later update.': 'Dette afsnit bliver tilgængeligt i en senere opdatering.',
    'Timezone': 'Tidszone',
    'Title': 'Titel',
    'Toggle full width': 'Skift fuld bredde',
    'Too many requests. Please wait a moment and try again.': 'For mange forespørgsler. Vent et øjeblik og prøv igen.',
    'Track RSVPs and export guest responses.': "Følg RSVP'er og eksportér gæstesvar.",
    'Track setup progress and jump to the next step for this invitation.': 'Følg opsætningsfremskridt og gå til næste trin for denne invitation.',
    'Type': 'Type',
    'Type %s to confirm permanent deletion': 'Skriv %s for at bekræfte permanent sletning',
    'Unpublish': 'Afpublicér',
    'Updated': 'Opdateret',
    'Upload photos': 'Upload fotos',
    'Uploading photos…': 'Uploader fotos…',
    'Venue name': 'Stednavn',
    'View details': 'Se detaljer',
    'View external wishlist': 'Se ekstern ønskeliste',
    'View order #%d': 'Se ordre #%d',
    'View product': 'Se produkt',
    'View project': 'Se projekt',
    'Visibility': 'Synlighed',
    'We could not save your response. Please try again.': 'Vi kunne ikke gemme dit svar. Prøv igen.',
    'We could not update the wishlist. Please try again.': 'Vi kunne ikke opdatere ønskelisten. Prøv igen.',
    'We could not upload your photos. Please try again.': 'Vi kunne ikke uploade dine fotos. Prøv igen.',
    'Welcome to your invitation project': 'Velkommen til dit invitationsprojekt',
    'When': 'Hvornår',
    'When you purchase or manage an online invitation, we store event details, guest lists, RSVP responses, optional wishlist reservations, and guest photo uploads you or your guests submit.': 'Når du køber eller administrerer en online invitation, gemmer vi begivenhedsdetaljer, gæstelister, RSVP-svar, valgfrie ønskelistereservationer og gæstefotos, som du eller dine gæster uploader.',
    'Where': 'Hvor',
    'Will you attend?': 'Deltager du?',
    'Wishlist': 'Ønskeliste',
    'Wishlist items': 'Ønskelistevarer',
    'Wishlist settings': 'Indstillinger for ønskeliste',
    'Wishlist updated.': 'Ønskeliste opdateret.',
    'WooCommerce online invitation projects with PDF Builder integration.': 'WooCommerce online invitationsprojekter med PDF Builder-integration.',
    'WooCommerce order records may be retained for legal and accounting purposes.': 'WooCommerce-ordrer kan opbevares af juridiske og regnskabsmæssige årsager.',
    'Yes': 'Ja',
    'You are invited': 'Du er inviteret',
    'You are invited to {event_title}': 'Du er inviteret til {event_title}',
    'You do not have any invitation projects yet.': 'Du har endnu ingen invitationsprojekter.',
    'You do not have permission to perform this action.': 'Du har ikke tilladelse til at udføre denne handling.',
    'You do not have permission to retry project imports.': 'Du har ikke tilladelse til at prøve projektimport igen.',
    'You do not have permission to view invitation projects.': 'Du har ikke tilladelse til at se invitationsprojekter.',
    'You may archive or permanently delete a project from My Account settings. WooCommerce order records may be retained separately for legal and accounting purposes.': 'Du kan arkivere eller permanent slette et projekt fra Min konto-indstillinger. WooCommerce-ordrer kan opbevares separat af juridiske og regnskabsmæssige årsager.',
    'Your customised design is ready to edit.': 'Dit tilpassede design er klar til redigering.',
    'Your demo invitation preview': 'Din demo-invitationsforhåndsvisning',
    'Your design was changed elsewhere. Reload the page and try again.': 'Dit design blev ændret et andet sted. Genindlæs siden og prøv igen.',
    'Your guest invitation data': 'Dine gæsteinvitationsdata',
    'Your invitation': 'Din invitation',
    'Your invitation is live': 'Din invitation er live',
    'Your invitation is published.': 'Din invitation er publiceret.',
    'Your invitation is unpublished.': 'Din invitation er afpubliceret.',
    'Your invitation project is ready': 'Dit invitationsprojekt er klar',
    'Your name': 'Dit navn',
    'Your response has been saved.': 'Dit svar er gemt.',
    'Your RSVP for {event_title}': 'Dit RSVP for {event_title}',
    'Your upload session expired. Please try again.': 'Din uploadsession er udløbet. Prøv igen.',
    'Your uploaded photos': 'Dine uploadede fotos',
    'Your wishlist reservations': 'Dine ønskelistereservationer',
    '“Sent” means accepted by wp_mail/mailer, not inbox delivery.': '«Sendt» betyder accepteret af wp_mail/mailer, ikke levering til indbakken.',
}

TRANSLATIONS.update(SUPPLEMENT)

# Plural forms: (singular, plural) for Danish n != 1 rule.
PLURAL_TRANSLATIONS: dict[str, tuple[str, str]] = {
    '%d guest added to this project.': ('%d gæst tilføjet til dette projekt.', '%d gæster tilføjet til dette projekt.'),
    '%d guest': ('%d gæst', '%d gæster'),
    '%d contact': ('%d kontakt', '%d kontakter'),
    '%d gift': ('%d gave', '%d gaver'),
    '%d photo': ('%d foto', '%d fotos'),
    '%d project': ('%d projekt', '%d projekter'),
    'This invitation is for %d guest. Please confirm how many will attend.': ('Denne invitation er til %d gæst. Bekræft venligst, hvor mange der deltager.', 'Denne invitation er til %d gæster. Bekræft venligst, hvor mange der deltager.'),
}

PO_HEADER = {
    "Project-Id-Version": "Prikogstreg Online Invitations 0.1.0",
    "Report-Msgid-Bugs-To": "https://wordpress.org/support/plugin/prikogstreg-online-invitations",
    "Language": "da_DK",
    "MIME-Version": "1.0",
    "Content-Type": "text/plain; charset=UTF-8",
    "Content-Transfer-Encoding": "8bit",
    "Plural-Forms": "nplurals=2; plural=(n != 1);",
    "X-Domain": "prikogstreg-online-invitations",
}


def build_po() -> tuple[int, int, list[str]]:
    """Return (translated_count, total_count, missing_msgids)."""
    if not POT_FILE.is_file():
        raise FileNotFoundError(f"POT file not found: {POT_FILE}")

    pot = polib.pofile(str(POT_FILE))
    po = polib.POFile()
    po.metadata = dict(PO_HEADER)

    if pot.metadata.get("POT-Creation-Date"):
        po.metadata["POT-Creation-Date"] = pot.metadata["POT-Creation-Date"]
    if pot.metadata.get("PO-Revision-Date"):
        po.metadata["PO-Revision-Date"] = pot.metadata["PO-Revision-Date"]

    missing: list[str] = []
    translated = 0
    total = 0

    for entry in pot:
        if entry.obsolete:
            continue

        new_entry = polib.POEntry(
            msgid=entry.msgid,
            msgid_plural=entry.msgid_plural,
            msgctxt=entry.msgctxt,
            occurrences=entry.occurrences,
            comment=entry.comment,
            tcomment=entry.tcomment,
            flags=entry.flags,
            previous_msgid=entry.previous_msgid,
            previous_msgid_plural=entry.previous_msgid_plural,
            previous_msgctxt=entry.previous_msgctxt,
        )

        if not entry.msgid:
            po.append(new_entry)
            continue

        total += 1

        if entry.msgid_plural:
            forms = PLURAL_TRANSLATIONS.get(entry.msgid)
            if forms:
                new_entry.msgstr_plural = {0: forms[0], 1: forms[1]}
                translated += 1
            else:
                missing.append(entry.msgid)
        else:
            msgstr = TRANSLATIONS.get(entry.msgid)
            if msgstr is not None:
                new_entry.msgstr = msgstr
                translated += 1
            else:
                missing.append(entry.msgid)

        po.append(new_entry)

    PO_FILE.parent.mkdir(parents=True, exist_ok=True)
    po.save(str(PO_FILE))
    return translated, total, missing


def compile_mo() -> None:
    result = subprocess.run(
        ["msgfmt", "--statistics", "-o", str(MO_FILE), str(PO_FILE)],
        capture_output=True,
        text=True,
        check=False,
    )
    stats = (result.stderr or result.stdout or "").strip()
    if result.returncode != 0:
        print(stats, file=sys.stderr)
        raise RuntimeError(f"msgfmt failed with exit code {result.returncode}")
    print(stats)


def cleanup_bak() -> None:
    if BAK_FILE.is_file():
        BAK_FILE.unlink()


def main() -> int:
    translated, total, missing = build_po()
    print(f"PO written: {PO_FILE}")
    print(f"Translated {translated} of {total} strings")
    if missing:
        print("Missing translations:", file=sys.stderr)
        for msgid in missing:
            print(f"  - {msgid!r}", file=sys.stderr)
        return 1
    compile_mo()
    print(f"MO written: {MO_FILE}")
    cleanup_bak()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

